# vim:fileencoding=utf-8:foldmethod=marker

macos_titlebar_color dark

font_size 20
font_family FiraCodeNFM-Ret
bold_font FiraCodeNFM-Bold
font_features FiraCodeNFM-Ret +zero +onum

tab_bar_edge top
tab_bar_style slant
tab_bar_align left

macos_quit_when_last_window_closed no
macos_traditional_fullscreen yes
